# Generated by Django 4.2.1 on 2023-05-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image')),
                ('name_product', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('category', models.CharField(max_length=30, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
